version: '3.8'

services:
  app:
    build: .
    ports:
      - "7860:3000" # Mapea el puerto local 7860 al puerto 3000 del contenedor
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always